// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkW9yPG01oNl8SepinNn191-Nhc4CSq34',
    appId: '1:365719601513:web:374df4281451988863bdf8',
    messagingSenderId: '365719601513',
    projectId: 'practice-flutter-firebas-d8616',
    authDomain: 'practice-flutter-firebas-d8616.firebaseapp.com',
    storageBucket: 'practice-flutter-firebas-d8616.appspot.com',
    measurementId: 'G-7F7W598GFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiiWwwzyKJrRoiQ6kMoa6pf9ubmch335Q',
    appId: '1:365719601513:android:c216234ffb460fb163bdf8',
    messagingSenderId: '365719601513',
    projectId: 'practice-flutter-firebas-d8616',
    storageBucket: 'practice-flutter-firebas-d8616.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCALeHuAW3gBR54rpjytJodhd0DaLWrv5Q',
    appId: '1:365719601513:ios:8694dbc1f20356e363bdf8',
    messagingSenderId: '365719601513',
    projectId: 'practice-flutter-firebas-d8616',
    storageBucket: 'practice-flutter-firebas-d8616.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCALeHuAW3gBR54rpjytJodhd0DaLWrv5Q',
    appId: '1:365719601513:ios:8694dbc1f20356e363bdf8',
    messagingSenderId: '365719601513',
    projectId: 'practice-flutter-firebas-d8616',
    storageBucket: 'practice-flutter-firebas-d8616.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkW9yPG01oNl8SepinNn191-Nhc4CSq34',
    appId: '1:365719601513:web:e19826dc081ce80863bdf8',
    messagingSenderId: '365719601513',
    projectId: 'practice-flutter-firebas-d8616',
    authDomain: 'practice-flutter-firebas-d8616.firebaseapp.com',
    storageBucket: 'practice-flutter-firebas-d8616.appspot.com',
    measurementId: 'G-LCYBDM2ZTM',
  );
}
